# Application Configuration
spring.application.name=security-service
server.port=8081

# Database Configuration (MySQL - Adjust as per your setup)
# spring.datasource.url=jdbc:mysql://localhost:3306/smart_analyzer?createDatabaseIfNotExist=true
# spring.datasource.username=root
# spring.datasource.password=root
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# H2 Database (Using H2 by default - File Based for persistence)
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
smart.app.jwtSecret=======================SmartAnalyzerSecretKey===========================
smart.app.jwtExpirationMs=86400000
