# Generated by Django 6.0.4 on 2026-04-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_pricehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_info',
        ),
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
