# Generated by Django 6.0.4 on 2026-04-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_remove_product_seller_info_product_reviews_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
